### PR TITLE
Idna options

### LINKED ISSUE #234: Add ability for control IDNA options for idn_to_(utf8|ascii)  function
## Issue summary

The trouble happens when i try convert domains with some specific characters called "deviations" in my case is ß (more information in http://unicode.org/reports/tr46/#Transition_Considerations)

### System informations

| Information | Description |
|--------------|---------|
| Pdp version | 5.4 |
| PHP version | 7.3 |
| OS Platform |  Archlinux|

## Standalone code, or other way to reproduce the problem

```php

$domainName = 'faß.de';
$domain = new \Pdp\Domain($domainName);
echo $domain->getContent();
//fass.de 
echo $domain->toUnicode()->getContent();
//fass.de 
echo $domain->toAscii()->getContent();
//fass.de 
```

### Expected result

In my case i expect to get "faß.de" as unicode and xn--fa-hia.de as ascii
This happens because function idn_to_utf8 https://github.com/jeremykendall/php-domain-parser/blob/develop/src/IDNAConverterTrait.php#L149 and idn_to_acii https://github.com/jeremykendall/php-domain-parser/blob/develop/src/IDNAConverterTrait.php#L118    used with option = 0;

But for expected result  option IDNA_NONTRANSITIONAL_TO_UNICODE (32) required for   idn_to_utf8  and IDNA_NONTRANSITIONAL_TO_ASCII for idn_to_acii
https://www.php.net/manual/en/intl.constants.php

```php
       $domainName = 'faß.de';
        $info  = [];
        $utf1 = idn_to_utf8($domainName, IDNA_DEFAULT , INTL_IDNA_VARIANT_UTS46, $info);
        $utf2 = idn_to_utf8($domainName, IDNA_NONTRANSITIONAL_TO_UNICODE , INTL_IDNA_VARIANT_UTS46);
        expect($info['isTransitionalDifferent'])->true();
        expect($utf1)->equals('fass.de');
        expect($utf2)->equals('faß.de');

        $ascii1 = idn_to_ascii($domainName, IDNA_DEFAULT, INTL_IDNA_VARIANT_UTS46, $info);
        $ascii2 = idn_to_ascii($domainName, IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46);
    
        expect($ascii1)->equals('fass.de');
        expect($ascii2)->equals('xn--fa-hia.de');
```
 
So i want to have ability to set my custom option for idn convertation. I can make PR if we agree on how to pass this option.  Or it can be used as default;
with IDNA_DEFAULT option - idn_to_ascii for fass.de and  faß.de - are same and it can provide some unexpected behavior
Also it will be good to have method for checking is domainName contains deviation characters

### PR DESCRIPTION
**Pull request by Insolita**
fix #234 
valid branch for #235

### CODE REVIEW

File: src/Domain.php [hunk 1]
```diff
@@ -20,6 +20,7 @@
 use Pdp\Exception\CouldNotResolveSubDomain;
 use Pdp\Exception\InvalidLabel;
 use Pdp\Exception\InvalidLabelKey;
+use Throwable;
```
Comment (nyamsprod) [inline src/Domain.php]: `Throwable` is no longer used in the class.

File: src/DomainInterface.php [hunk 2]
```diff
@@ -99,4 +99,11 @@ public function toUnicode();
      * from the right-most label to the left-most label.
      */
     public function getIterator();
+    
+    /**
+     * return true if domain contains deviation characters.
+     * @see http://unicode.org/reports/tr46/#Transition_Considerations
+     * @return bool
+     **/
+    public function isTransitionalDifferent(): bool;
```
Comment (nyamsprod) [inline src/DomainInterface.php]: Adding this method to the interface should be postponed for the next major release because you are modifying the public API of the interface if someone already has this method implemented it's BC break for him.

File: src/IDNAConverterTrait.php [hunk 3]
```diff
@@ -28,6 +29,7 @@
 use function iterator_to_array;
 use function method_exists;
 use function preg_match;
+use function property_exists;
```
Comment (nyamsprod) [inline src/IDNAConverterTrait.php]: no longer in used

File: src/Domain.php (hunk 1 above)
Comment (nyamsprod) [reply src/Domain.php]: you should use the following command lines
```
 ./vendor/bin/php-cs-fixer fix -vvv --allow-risky=yes
composer phpstan
```

Prior to committing your changes on your local machine these command will:

- fixes any potential coding style issue
- uses PHPStan to analyze and improve your code

**Comment by Insolita** [comment]
> in all methods from the Manager class so that they are defined only once per call
why not in constructor too?

**Comment by Insolita** [comment]
>the generate cache key should also reflect the IDNA options chosen so that the correct cache is built and fetch on call.

As i see, tlds and public suffixes not contains ambiguous characters, the problem occurs with labels only, so it not sensitive for cached/not cached data

**Comment by nyamsprod** [comment]
> Why not in constructor too?

Because the Manager is a builder so It does not need to restrict the type of Rules and TopLevelDomains it will create

> As i see, tlds and public suffixes not contains ambiguous characters, the problem occurs with labels only, so it not sensitive for cached/not cached data

Then the cache key won't be affected only the `Rules` and the `TopLevelDomains` classes should inherit the idna options to correctly resolve labels.

So my example stay correct only there's less changes to be made we only need to pass idna options to the returned classes 👍

**Comment by nyamsprod** [comment]
I'll try to review it this night again but looks already pretty good right now 👍 . Once merged, it will be a great minor release. Already thanks for the PR 😉

File: src/IDNAConverterTrait.php [hunk 4]
```diff
@@ -222,9 +224,19 @@ private function setLabels($domain = null): array
...
+        return array_reverse(explode('.', $this->idnToUnicode($ascii_domain, $unicodeOption)));
+    }
+    
+    private function hasTransitionalDifference($domain):bool
+    {
+        if(!is_string($domain) || empty($domain)){
+            return false;
+        }
+        $info = [];
+        idn_to_ascii($domain, IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46, $info);
```
Comment (nyamsprod) [inline src/IDNAConverterTrait.php]: I'm wondering if we should not refactor this line so that `idn_to_ascii` is only use once with all the checks in the trait 🤔 .  so idnToAscii and hasTransitonalDifference uses the same method ? What do you think this way maintenance becomes easier in case of bugfix or improvement ?

Comment (Insolita) [reply src/IDNAConverterTrait.php]: this method is not so heavy and not raise additional exceptions; In previous variant we use it once and save state in private property, but it  provide additional problems https://github.com/jeremykendall/php-domain-parser/pull/235#discussion_r273705257

Comment (nyamsprod) [reply src/IDNAConverterTrait.php]: I was thinking of something along these lines:

```php
    private function idnToAscii(string $domain, int $options): string
    {
    	list($domain, $isTransitionalDifferent) = $this->transformToAscii($domain, $options);

    	return $domain;
    }

	private function hasTransitionalDifference($domain):bool
	{
	        if (!is_string($domain) || empty($domain)){
	            return false;
	        }

	        list($domain, $isTransitionalDifferent) = $this->transformToAscii($domain, $options);

	        return $isTransitionalDifferent;
	    }
	}

	private function transformToAscii(string $domain, int $options): array
	{
        $domain = rawurldecode($domain);
        static $pattern = '/[^\x20-\x7f]/';
        if (!preg_match($pattern, $domain)) {
            return [strtolower($domain), false];
        }
        $output = idn_to_ascii($domain, 0, INTL_IDNA_VARIANT_UTS46, $arr);
        if (0 !== $arr['errors']) {
            throw new InvalidDomain(sprintf('The host `%s` is invalid : %s', $domain, self::getIdnErrors($arr['errors'])));
        }
        // @codeCoverageIgnoreStart
        if (false === $output) {
            throw new UnexpectedValueException(sprintf('The Intl extension is misconfigured for %s, please correct this issue before proceeding.', PHP_OS));
        }
        // @codeCoverageIgnoreEnd
        if (false === strpos($output, '%')) {
        	return [$output, $result['isTransitionalDifferent']];
        }
        
        throw new InvalidDomain(sprintf('The host `%s` is invalid: it contains invalid characters', $domain));	
	}
```

Comment (nyamsprod) [reply src/IDNAConverterTrait.php]: Also could you update your code to **NOT** use `empty` as I tend to remove its usage from the codebase. I generally prefer `[] === $array`  or clearly stating what domain is. Empty leads to error because the empty string and '0' are all considered empty :'(

**Comment by nyamsprod** [comment]
thanks for the PR and the great addition to the library @Insolita
